package com.cxb.storehelperserver.model;

public class TUser extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.idt_user
     *
     * @mbg.generated Tue Nov 29 01:40:03 CST 2022
     */
    private Integer idtUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.account
     *
     * @mbg.generated Tue Nov 29 01:40:03 CST 2022
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbg.generated Tue Nov 29 01:40:03 CST 2022
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.idt_user
     *
     * @return the value of t_user.idt_user
     *
     * @mbg.generated Tue Nov 29 01:40:03 CST 2022
     */
    public Integer getIdtUser() {
        return idtUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.idt_user
     *
     * @param idtUser the value for t_user.idt_user
     *
     * @mbg.generated Tue Nov 29 01:40:03 CST 2022
     */
    public void setIdtUser(Integer idtUser) {
        this.idtUser = idtUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.account
     *
     * @return the value of t_user.account
     *
     * @mbg.generated Tue Nov 29 01:40:03 CST 2022
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.account
     *
     * @param account the value for t_user.account
     *
     * @mbg.generated Tue Nov 29 01:40:03 CST 2022
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password
     *
     * @return the value of t_user.password
     *
     * @mbg.generated Tue Nov 29 01:40:03 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password
     *
     * @param password the value for t_user.password
     *
     * @mbg.generated Tue Nov 29 01:40:03 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}