package com.cxb.storehelperserver.mapper;

import com.cxb.storehelperserver.model.TUser;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface TUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Tue Nov 29 01:40:03 CST 2022
     */
    @Delete({
        "delete from t_user",
        "where idt_user = #{idtUser,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer idtUser);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Tue Nov 29 01:40:03 CST 2022
     */
    @Insert({
        "insert into t_user (idt_user, account, ",
        "password)",
        "values (#{idtUser,jdbcType=INTEGER}, #{account,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR})"
    })
    int insert(TUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Tue Nov 29 01:40:03 CST 2022
     */
    @Select({
        "select",
        "idt_user, account, password",
        "from t_user",
        "where idt_user = #{idtUser,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="idt_user", property="idtUser", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="account", property="account", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR)
    })
    TUser selectByPrimaryKey(Integer idtUser);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Tue Nov 29 01:40:03 CST 2022
     */
    @Select({
        "select",
        "idt_user, account, password",
        "from t_user"
    })
    @Results({
        @Result(column="idt_user", property="idtUser", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="account", property="account", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR)
    })
    List<TUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Tue Nov 29 01:40:03 CST 2022
     */
    @Update({
        "update t_user",
        "set account = #{account,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR}",
        "where idt_user = #{idtUser,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TUser row);
}